name: Documentation update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy documentation
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/markdown'
          destination_repo: 'crisjf/action-target'
          destination_folder: 'cs_brix/docs'
          user_email: 'crisjf@mit.edu'
          user_name: 'crisjf'
