name: Alert parent repository on push

on: 
  workflow_dispatch:

jobs:
  build:
    name: Dispatch to action-target
    runs-on: ubuntu-latest
    steps:
      - name: Alert parent repo
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repo: cityscope.github.io
          owner: CityScope
          event_type: docs_update